INSERT INTO markers (title, description, thumbnail_url, map_id, location, owner_id)
VALUES

('Vice & Virtue Joint',  'This is also reflected in the countrys flag, which has three vertical stripes in dark yellow, brown and light brown. Their coat of arms are two arrows with two smaller spiritual symbols on either side', 'https://picsum.photos/200', 1 , point(-70, 31), 5),
('Javawocky Espresso Bar', 'Bordered between large rock formations to the North, a wide river to the South, a wild river to the East and a small ocean to the West, the country of Ostax mainly lives off beer brewing, crafting and wood production.', 'https://picsum.photos/200', 1 , point(11, -128), 5),
('Bacon & Eggs Cafe', 'Ostax itself is mainly covered in uninhabitable wastelands and has a dry climate, which has lead to a tightly concentrated population, despite the number of people, which means most of them live in large villages.', 'https://picsum.photos/200', 1 , point(-75, 60), 5),
('Hallowed Grounds Tearoom', 'The countrys landscape is sinister; dangerous mountains, wild rivers and forgotten farmlands are just a sliver of the foulness Ostax has to offer, which is why the country is shirked among foreigners.', 'https://picsum.photos/200', 1 , point(84, 90), 5),
('Hot Shots Joint', 'The people of Ostax are unreceptive towards foreigners and tend to welcome them with detachment. They feel foreigners could block the countrys well being.', 'https://picsum.photos/200', 1 , point(-63, -156), 5),
('Divine Eden Coffee Shop', 'Ostax has resolute laws and law enforcement, which is expected in their circumstances. The people are troubled due to failing crops, caused by irrational fears and superstitions.', 'https://picsum.photos/200', 1 , point(65, -92), 11),
('Homey Java Lunchroom', 'This is also reflected in the countrys flag, which has three vertical stripes in dark yellow, brown and light brown. Their coat of arms are two arrows with two smaller spiritual symbols on either side', 'https://picsum.photos/200', 1 , point(68, 138), 11),
('Quiet Fruits Joint', 'Bordered between large rock formations to the North, a wide river to the South, a wild river to the East and a small ocean to the West, the country of Ostax mainly lives off beer brewing, crafting and wood production.', 'https://picsum.photos/200', 1 , point(70, 154), 11),
('Olive Oasis Cafeteria', 'Ostax itself is mainly covered in uninhabitable wastelands and has a dry climate, which has lead to a tightly concentrated population, despite the number of people, which means most of them live in large villages.', 'https://picsum.photos/200', 1 , point(78, -24), 11),
('Flying Hat Coffee', 'The countrys landscape is sinister; dangerous mountains, wild rivers and forgotten farmlands are just a sliver of the foulness Ostax has to offer, which is why the country is shirked among foreigners.', 'https://picsum.photos/200', 1 , point(44, -128), 11),

('The Matrix Casino', 'The people of Ostax are unreceptive towards foreigners and tend to welcome them with detachment. They feel foreigners could block the countrys well being.', 'https://picsum.photos/200', 2 , point(16, 158), 15),
('The Cub', 'Ostax has resolute laws and law enforcement, which is expected in their circumstances. The people are troubled due to failing crops, caused by irrational fears and superstitions.', 'https://picsum.photos/200', 2 , point(-16, 117), 15),
('The Rhythm Casino', 'This is also reflected in the countrys flag, which has three vertical stripes in dark yellow, brown and light brown. Their coat of arms are two arrows with two smaller spiritual symbols on either side', 'https://picsum.photos/200', 2 , point(-40, 129), 15),
('The Felicity Casino','Twelve skinny, square towers dominate the sky line of this massive castle and are connected by fairly low, wide walls made of blue stone.', 'https://picsum.photos/200', 2 , point(70, 81), 15),
('The Hyacinth','Elegant windows are scattered generously around the walls in seeminly perfect symmetry, along with huge crenelations for archers and artillery.', 'https://picsum.photos/200', 2 , point(81, 135), 15),
('The Azure Archway Casino','A huge gate with giant metal doors, a draw bridge and archer holes offers a safe home to all those in need in these cold mountains and its the only easy way in, any other side would be futile.', 'https://picsum.photos/200', 2 , point(-90, 150), 12),
('The Eastern Cloak Casino','Large boulders litter the fields outside the castle, paths to and from the castle snake around them and farm plots are small and scattered all around. This castle looks very new, but without knowing its history its impossible to tell if its a newly build castle or a well kept one.', 'https://picsum.photos/200', 2 , point(53, 55), 12),
('The Silk Nimbus Casino','Seven slim, square towers dominate the sky line of this massive castle and are connected by big, heavy walls made of grey stone.', 'https://picsum.photos/200', 2 , point(34, -106), 12),
('The Ruby Stallion Casino','Ornate windows are scattered generously around the walls in seeminly perfect symmetry, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 2 , point(18, 99), 12),
('The Paradise Tempest Casino','A sizable gate with enormous metal doors, a regular bridge and a moat guards the inhabitants of this island castle, but its not the only way in, but itll be your best shot if you wish to conquer this castle.', 'https://picsum.photos/200', 2 , point(59, 86), 12),

('Global Library','Eleven narrow, square towers surround the castle, they reach twice the height of the walls and are connected by strengthened, thick walls made of obsidian.', 'https://picsum.photos/200', 3 , point(5, -123), 16),
('Crest Bibliotheca','Elegant windows are scattered generously across the walls in an asymmetric pattern, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 3 , point(-37, -124), 16),
('Innovation Athenaeum','A great gate with giant wooden doors and hot oil pots guards the only passage into the castle build upon a mountain top, but its not the only way in, which fortunately only very few know.', 'https://picsum.photos/200', 3 , point(12, 65), 16),
('Scholars Library','Trees grow close to the castle gates and provide it with valuable wood for all sorts of purposes. This castle has clearly stood the test of time, the rocks of the walls are aged and vines and plants grow inside the cracks, but this castle will last for ages to come.', 'https://picsum.photos/200', 3 , point(73, -125), 16),
('Discovery Library','Bordered between a canal to the North, a mountain range to the South, huge mountains to the East and fertile grounds to the West, the country of Asharia mainly lives off fletching, woodcrafting and carpenting.', 'https://picsum.photos/200', 3 , point(-78, -90), 16),
('Curio Library','Asharia itself is mainly covered in sand plains and has a warm climate, which has lead to a congested population, despite the number of people, which means most of them live in megalopolises.', 'https://picsum.photos/200', 3 , point(6, 87), 13),
('Quest Athenaeum','The countrys landscape is elegant; calm lakes, neverending fields of green and gorgeous flower fields are just a sliver of the splendor Asharia has to offer, which is why the country is popular among foreigners.', 'https://picsum.photos/200', 3 , point(27, -154), 13),
('Savant Library','The people of Asharia are unpleasant towards foreigners and tend to welcome them with disintrest. They feel foreigners could further ruin the countrys well being.', 'https://picsum.photos/200', 3 , point(70, -160), 13),
('Illusions Library','Asharia has tight laws and law enforcement, which is quite normal. The people are unsatisfied due to deteriorating infrastructure, caused by technological setbacks.', 'https://picsum.photos/200', 3 , point(40, 5), 13),
('Chimera Athenaeum','This is also reflected in the countrys flag, which has three vertical stripes in purple, white and gold. Their coat of arms is a birds claw on a square', 'https://picsum.photos/200', 3 , point(28, 150), 13),

('The Flock - Animal Shelter','Athea itself is mainly covered in flatlands and has a calm climate, which has lead to a tightly concentrated population, despite the number of people, which means most of them live in cities.', 'https://picsum.photos/200', 4 , point(12, -54), 2),
('The Woofer - Animal Sanctuary','The countrys landscape is colorful; steep, magnificent mountains, gorgeous flower fields and misty mountains are just a sliver of the wealth of beauty Athea has to offer, which is why the country is admired among foreigners.', 'https://picsum.photos/200', 4 , point(23, 116), 2),
('Pawing Packs - Pet Haven','The people of Athea are helpful towards foreigners and tend to welcome them with a bright smile. They feel foreigners could nourish the countrys well being.', 'https://picsum.photos/200', 4 , point(87, 51), 2),
('Wag Time - Exotic Pets','Athea has rough laws and law enforcement, which is predictable. The people are unconcerend due to their healthy lives, thanks to fortunate natural properties.', 'https://picsum.photos/200', 4 , point(-60, 0), 2),
('Endless Pawsabilities - Animal Care Center','This is also reflected in the countrys flag, which has three horizontal stripes and a circle in dark gold and light purple. Their coat of arms is a chicken on top of a mountain', 'https://picsum.photos/200', 4 , point(-61, 71), 2),
('Release the Hounds - Exotic Pets','Twelve skinny, square towers dominate the sky line of this massive castle and are connected by fairly low, wide walls made of blue stone.', 'https://picsum.photos/200', 4 , point(-30, -167), 14),
('Natural Critters - Pet Shop','Elegant windows are scattered generously around the walls in seeminly perfect symmetry, along with huge crenelations for archers and artillery.', 'https://picsum.photos/200', 4 , point(28, -13), 14),
('Hot Dogs - Animal Care','A huge gate with giant metal doors, a draw bridge and archer holes offers a safe home to all those in need in these cold mountains and its the only easy way in, any other side would be futile.', 'https://picsum.photos/200', 4 , point(-61, 39), 14),
('Barking Barber - Pet Health','Large boulders litter the fields outside the castle, paths to and from the castle snake around them and farm plots are small and scattered all around. This castle looks very new, but without knowing its history its impossible to tell if its a newly build castle or a well kept one.', 'https://picsum.photos/200', 4 , point(74, 7), 14),
('Pooch Parlor - Pet Care','Seven slim, square towers dominate the sky line of this massive castle and are connected by big, heavy walls made of grey stone.', 'https://picsum.photos/200', 4 , point(57, 151), 14),

('Dunstead Hold','A sizable gate with enormous metal doors, a regular bridge and a moat guards the inhabitants of this island castle, but its not the only way in, but itll be your best shot if you wish to conquer this castle.', 'https://picsum.photos/200', 5 , point(-19, -25), 6),
('Paelford Citadel','Remnants of broken siege engines, swords and shields litter the fields outside, a painful reminder of a past war. This castle shows signs of expansion as some parts are clearly build more recently than others, the inhabitants are already working on another part and hope to keep expanding.', 'https://picsum.photos/200', 5 , point(61, 25), 6),
('Merryport Hold','Eleven narrow, square towers surround the castle, they reach twice the height of the walls and are connected by strengthened, thick walls made of obsidian.', 'https://picsum.photos/200', 5 , point(-67, 136), 6),
('Staerdale Palace','Elegant windows are scattered generously across the walls in an asymmetric pattern, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 5 , point(-20, 105), 6),
('Barnsil Castle','A great gate with giant wooden doors and hot oil pots guards the only passage into the castle build upon a mountain top, but its not the only way in, which fortunately only very few know.', 'https://picsum.photos/200', 5 , point(23, -170), 6),
('Earlington Stronghold','Trees grow close to the castle gates and provide it with valuable wood for all sorts of purposes. This castle has clearly stood the test of time, the rocks of the walls are aged and vines and plants grow inside the cracks, but this castle will last for ages to come.', 'https://picsum.photos/200', 5 , point(-47, -179), 15),
('Santhope Palace','Bordered between a canal to the North, a mountain range to the South, huge mountains to the East and fertile grounds to the West, the country of Asharia mainly lives off fletching, woodcrafting and carpenting.', 'https://picsum.photos/200', 5 , point(70, -170), 15),
('Hurlton Citadel','Asharia itself is mainly covered in sand plains and has a warm climate, which has lead to a congested population, despite the number of people, which means most of them live in megalopolises.', 'https://picsum.photos/200', 5 , point(33, -123), 15),
('Flatwick Palace','The countrys landscape is elegant; calm lakes, neverending fields of green and gorgeous flower fields are just a sliver of the splendor Asharia has to offer, which is why the country is popular among foreigners.', 'https://picsum.photos/200', 5 , point(18, -132), 15),
('Faerdham Castle','The people of Asharia are unpleasant towards foreigners and tend to welcome them with disintrest. They feel foreigners could further ruin the countrys well being.', 'https://picsum.photos/200', 5 , point(49, 13), 15),

('Pantheon Of Legends','This is also reflected in the countrys flag, which has three vertical stripes in purple, white and gold. Their coat of arms is a birds claw on a square', 'https://picsum.photos/200', 6 , point(-30, -174), 12),
('Sanctum Of The World','Bordered between fjords to the North, rich forests to the South, a small mountain range to the East and huge, open plains to the West, the country of Athea mainly lives off carpenting, leatherworking and fletching.', 'https://picsum.photos/200', 6 , point(-7, 14), 12),
('Pantheon Of Thirst','Athea itself is mainly covered in flatlands and has a calm climate, which has lead to a tightly concentrated population, despite the number of people, which means most of them live in cities.', 'https://picsum.photos/200', 6 , point(19, 63), 12),
('Temple Of Todohr','The countrys landscape is colorful; steep, magnificent mountains, gorgeous flower fields and misty mountains are just a sliver of the wealth of beauty Athea has to offer, which is why the country is admired among foreigners.', 'https://picsum.photos/200', 6 , point(42, -29), 12),
('Church Of Opmos','The people of Athea are helpful towards foreigners and tend to welcome them with a bright smile. They feel foreigners could nourish the countrys well being.', 'https://picsum.photos/200', 6 , point(-76, 75), 12),
('The Corrupted Mosque','Athea has rough laws and law enforcement, which is predictable. The people are unconcerend due to their healthy lives, thanks to fortunate natural properties.', 'https://picsum.photos/200', 6 , point(18, -121), 12),
('The Cardinal Altar','This is also reflected in the countrys flag, which has three horizontal stripes and a circle in dark gold and light purple. Their coat of arms is a chicken on top of a mountain', 'https://picsum.photos/200', 6 , point(-20, -101), 12),
('The Primal Summit', 'Twelve skinny, square towers dominate the sky line of this massive castle and are connected by fairly low, wide walls made of blue stone.', 'https://picsum.photos/200', 6 , point(-87, 90), 12),
('The Xeblappeion', 'Elegant windows are scattered generously around the walls in seeminly perfect symmetry, along with huge crenelations for archers and artillery.', 'https://picsum.photos/200', 6 , point(-26, -60), 12),
('The Ephenis', 'A huge gate with giant metal doors, a draw bridge and archer holes offers a safe home to all those in need in these cold mountains and its the only easy way in, any other side would be futile.', 'https://picsum.photos/200', 6 , point(-41, -136), 12),

('Wolfbrace Burrow', 'Seven slim, square towers dominate the sky line of this massive castle and are connected by big, heavy walls made of grey stone.', 'https://picsum.photos/200', 7 , point(-90, -12), 15),
('Crestbond Sanctuary', 'Ornate windows are scattered generously around the walls in seeminly perfect symmetry, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 7 , point(6, 72), 15),
('Highland Cave', 'A sizable gate with enormous metal doors, a regular bridge and a moat guards the inhabitants of this island castle, but its not the only way in, but itll be your best shot if you wish to conquer this castle.', 'https://picsum.photos/200', 7 , point(-19, -40), 15),
('Froststar Den', 'Remnants of broken siege engines, swords and shields litter the fields outside, a painful reminder of a past war. This castle shows signs of expansion as some parts are clearly build more recently than others, the inhabitants are already working on another part and hope to keep expanding.', 'https://picsum.photos/200', 7 , point(-86, 16), 15),
('Grassmight Base', 'Eleven narrow, square towers surround the castle, they reach twice the height of the walls and are connected by strengthened, thick walls made of obsidian.', 'https://picsum.photos/200', 7 , point(-29, 137), 15),
('The Sisterhood Base', 'Elegant windows are scattered generously across the walls in an asymmetric pattern, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 7 , point(74, -179), 15),
('The Epoch Retreat', 'A great gate with giant wooden doors and hot oil pots guards the only passage into the castle build upon a mountain top, but its not the only way in, which fortunately only very few know.', 'https://picsum.photos/200', 7 , point(74, -48), 15),
('The Arch Covert', 'Trees grow close to the castle gates and provide it with valuable wood for all sorts of purposes. This castle has clearly stood the test of time, the rocks of the walls are aged and vines and plants grow inside the cracks, but this castle will last for ages to come.', 'https://picsum.photos/200', 7 , point(-72, -115), 15),
('The Outlandish Burrow', 'Bordered between a canal to the North, a mountain range to the South, huge mountains to the East and fertile grounds to the West, the country of Asharia mainly lives off fletching, woodcrafting and carpenting.', 'https://picsum.photos/200', 7 , point(36, 8), 15),
('The Arachnid Cover', 'Asharia itself is mainly covered in sand plains and has a warm climate, which has lead to a congested population, despite the number of people, which means most of them live in megalopolises.', 'https://picsum.photos/200', 7 , point(-65, -127), 15),

('Stealf Row', 'Asharia has tight laws and law enforcement, which is quite normal. The people are unsatisfied due to deteriorating infrastructure, caused by technological setbacks.', 'https://picsum.photos/200', 8 , point(-40, -79), 9),
('Upper West Sphist', 'This is also reflected in the countrys flag, which has three vertical stripes in purple, white and gold. Their coat of arms is a birds claw on a square', 'https://picsum.photos/200', 8 , point(-20, 161), 9),
('Lower South Scircob', 'Bordered between fjords to the North, rich forests to the South, a small mountain range to the East and huge, open plains to the West, the country of Athea mainly lives off carpenting, leatherworking and fletching.', 'https://picsum.photos/200', 8 , point(-43, -33), 9),
('Upper East Leblult', 'Athea itself is mainly covered in flatlands and has a calm climate, which has lead to a tightly concentrated population, despite the number of people, which means most of them live in cities.', 'https://picsum.photos/200', 8 , point(63, 156), 9),
('Tirok Acre', 'The countrys landscape is colorful; steep, magnificent mountains, gorgeous flower fields and misty mountains are just a sliver of the wealth of beauty Athea has to offer, which is why the country is admired among foreigners.', 'https://picsum.photos/200', 8 , point(56, 161), 9),
('Upper Diggaip', 'The people of Athea are helpful towards foreigners and tend to welcome them with a bright smile. They feel foreigners could nourish the countrys well being.', 'https://picsum.photos/200', 8 , point(-38, -71), 9),
('Splihoft Market', 'Athea has rough laws and law enforcement, which is predictable. The people are unconcerend due to their healthy lives, thanks to fortunate natural properties.', 'https://picsum.photos/200', 8 , point(-74, 87), 9),
('South Strohil', 'This is also reflected in the countrys flag, which has three horizontal stripes and a circle in dark gold and light purple. Their coat of arms is a chicken on top of a mountain', 'https://picsum.photos/200', 8 , point(61, 26), 9),
('Rorreagweol Square', 'Twelve skinny, square towers dominate the sky line of this massive castle and are connected by fairly low, wide walls made of blue stone.', 'https://picsum.photos/200', 8 , point(-56, -4), 9),
('Swoaffilrord Row', 'Elegant windows are scattered generously around the walls in seeminly perfect symmetry, along with huge crenelations for archers and artillery.', 'https://picsum.photos/200', 8 , point(90, -47), 9),

('Shifted Polarity', 'Large boulders litter the fields outside the castle, paths to and from the castle snake around them and farm plots are small and scattered all around. This castle looks very new, but without knowing its history its impossible to tell if its a newly build castle or a well kept one.', 'https://picsum.photos/200', 9 , point(10, -118), 20),
('Gobl-Inn', 'Seven slim, square towers dominate the sky line of this massive castle and are connected by big, heavy walls made of grey stone.', 'https://picsum.photos/200', 9 , point(80, 165), 20),
('The Book of Riddles', 'Ornate windows are scattered generously around the walls in seeminly perfect symmetry, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 9 , point(-59, -104), 20),
('The Arcane Barrier', 'A sizable gate with enormous metal doors, a regular bridge and a moat guards the inhabitants of this island castle, but its not the only way in, but itll be your best shot if you wish to conquer this castle.', 'https://picsum.photos/200', 9 , point(2, -114), 20),
('The Time Warp', 'Remnants of broken siege engines, swords and shields litter the fields outside, a painful reminder of a past war. This castle shows signs of expansion as some parts are clearly build more recently than others, the inhabitants are already working on another part and hope to keep expanding.', 'https://picsum.photos/200', 9 , point(-62, -107), 20),
('The Expert Ent', 'Eleven narrow, square towers surround the castle, they reach twice the height of the walls and are connected by strengthened, thick walls made of obsidian.', 'https://picsum.photos/200', 9 , point(68, 99), 20),
('The Laughing Hobgoblin', 'Elegant windows are scattered generously across the walls in an asymmetric pattern, along with symmetric holes for archers and artillery.', 'https://picsum.photos/200', 9 , point(-48, 43), 20),
('The Elder Centaur', 'A great gate with giant wooden doors and hot oil pots guards the only passage into the castle build upon a mountain top, but its not the only way in, which fortunately only very few know.', 'https://picsum.photos/200', 9 , point(60, -65), 20),
('The Lazy Jackalope', 'Trees grow close to the castle gates and provide it with valuable wood for all sorts of purposes. This castle has clearly stood the test of time, the rocks of the walls are aged and vines and plants grow inside the cracks, but this castle will last for ages to come.', 'https://picsum.photos/200', 9 , point(19, 138), 20),
('The Scary Quill', 'Bordered between a canal to the North, a mountain range to the South, huge mountains to the East and fertile grounds to the West, the country of Asharia mainly lives off fletching, woodcrafting and carpenting.', 'https://picsum.photos/200', 9 , point(-15, -58), 20),

('The Olive Bond', 'The countrys landscape is elegant; calm lakes, neverending fields of green and gorgeous flower fields are just a sliver of the splendor Asharia has to offer, which is why the country is popular among foreigners.', 'https://picsum.photos/200', 10 , point(-41, 114), 5),
('The Enigma Fence', 'The people of Asharia are unpleasant towards foreigners and tend to welcome them with disintrest. They feel foreigners could further ruin the countrys well being.', 'https://picsum.photos/200', 10 , point(12, -72), 5),
('The Bitter Paradise', 'Asharia has tight laws and law enforcement, which is quite normal. The people are unsatisfied due to deteriorating infrastructure, caused by technological setbacks.', 'https://picsum.photos/200', 10 , point(-20, 91), 5),
('The Eastern Oyster', 'This is also reflected in the countrys flag, which has three vertical stripes in purple, white and gold. Their coat of arms is a birds claw on a square', 'https://picsum.photos/200', 10 , point(89, -132), 5),
('The Golden Front', 'Bordered between fjords to the North, rich forests to the South, a small mountain range to the East and huge, open plains to the West, the country of Athea mainly lives off carpenting, leatherworking and fletching.', 'https://picsum.photos/200', 10 , point(78, 65), 5),
('Vertigo', 'Athea itself is mainly covered in flatlands and has a calm climate, which has lead to a tightly concentrated population, despite the number of people, which means most of them live in cities.', 'https://picsum.photos/200', 10 , point(13, -145), 5),
('The Hive', 'The countrys landscape is colorful; steep, magnificent mountains, gorgeous flower fields and misty mountains are just a sliver of the wealth of beauty Athea has to offer, which is why the country is admired among foreigners.', 'https://picsum.photos/200', 10 , point(-80, -42), 5),
('Fluorescence', 'The people of Athea are helpful towards foreigners and tend to welcome them with a bright smile. They feel foreigners could nourish the countrys well being.', 'https://picsum.photos/200', 10 , point(20, -165), 5),
('The Boutique', 'Athea has rough laws and law enforcement, which is predictable. The people are unconcerend due to their healthy lives, thanks to fortunate natural properties.', 'https://picsum.photos/200', 10 , point(-6, -16), 5),
('Backstage', 'This is also reflected in the countrys flag, which has three horizontal stripes and a circle in dark gold and light purple. Their coat of arms is a chicken on top of a mountain', 'https://picsum.photos/200', 10 , point(-72, -174), 5);











