DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT Now(),
  last_updated TIMESTAMP NOT NULL DEFAULT Now(),
  share_url VARCHAR(255),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  private BOOLEAN NOT NULL DEFAULT TRUE,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_thumb VARCHAR(255)
);
