DROP TABLE IF EXISTS favorite_maps CASCADE;
DROP TABLE IF EXISTS collaborations CASCADE;

CREATE TABLE favorite_maps(
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);

CREATE TABLE collaborations (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
